config/routes.rb
require 'sidekiq/web'

AtlsRails::Application.routes.draw do
  root :to => 'high_voltage/pages#show', :id => 'index'
  devise_for :attendees, :controllers => { 
    :registrations => "attendees"}

  devise_scope :attendee do
    get '/attendees/new' => "attendees#new", :as => "sign_up"
  end


  get "profiles/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :blogs
  
  resources :orders

  resources :pretests

  resources :test_results

  resources :training_schedules, :only => [:index, :show]

  resources :trainings

  resources :events

  resources :news

  match "/trainings/:id/update_training_schedule" => "trainings#update_training_schedule", via: :put

  match "/home" => "homes#index"
  match "/home/test" => "homes#test"
  match "/home/start_test" => "homes#start_test"
  match "/home/finish_test" => "homes#finish_test"

  match "/home/profile/:id" => "homes#edit_profile", via: :get
  
  match "/home/profile/:id" => "homes#update_profile", via: :put

  match "/home/profile/:id/change_password" => "homes#change_password", via: :get

  match "/home/profile/:id/change_password" => "homes#update_password", via: :put

  match "/payment_term" => "homes#payment_terms"

  match "/payment_code" => "orders#payment_code"

  namespace :home do
    resources :post_tests do
      collection do 
        get :start_test
      end      
    end
  end


  mount Sidekiq::Web => '/sidekiq'

end

app/models/training.rb
class Training < ActiveRecord::Base
	attr_accessible :training_location, :attendee_id, :amount_paid, :amount_unpaid, :training_location_id, :training_schedule_id, :payment_type_id, :payment_code, :type, :status, :description, :payments_attributes, :group_number, :score
	attr_writer :current_step

	scope :by_training_schedule, lambda{|schedule| joins(:training).where('trainings.training_schedule_id = ?', schedule.id) }

	belongs_to :training_location
	belongs_to :attendee
	belongs_to :training_schedule

	belongs_to :payment_type
	has_many :payments

	has_many :post_test_results

	after_initialize :init
	accepts_nested_attributes_for :training_location, :payments

	PAYMENT_STATUSES = %w(Lunas Belum\ Lunas)	

	TRAINING_STATUSES = %w(Batal Aktif PostTest Lulus)

	TRAINING_TYPES = %w(RegularTraining RemedialTraining)

	PAYMENT_CODE_MOD_WEIGH = 200

	scope :sort_by_created_at, order("created_at desc")
	scope :post_test_trainings, where(status: Training::TRAINING_STATUSES[2])
	scope :active_trainings, where("status = ? OR status = ?", Training::TRAINING_STATUSES[1], Training::TRAINING_STATUSES[2])

	before_save :finish_training


	def init
		unless self.amount_paid
			self.amount_paid = 0			
		end		
	end


	# def self.create_initial_training(attributes)
	# 	training = Training.new(attributes.select{|s,value|value.nil? == false})
	# 	training.status = Training::TRAINING_STATUSES[1]
	# 	training.save
	# end

	def confirm_payment
		self.amount_paid = self.total_price
		self.save
	end

	def payment_done?
		unless training_location
			return false
		end
		if amount_paid >= training_location.price
			true
		else
			false
		end
	end


	def steps
		%w[details payment summary]
	end

	def current_step
		@current_step || steps.first
	end

	def next_step
		self.current_step = steps[steps.index(current_step)+1]
	end

	def previous_step
		self.current_step = steps[steps.index(current_step)-1]
	end

	def last_step?
		self.current_step == steps.last
	end

	def first_step?
		self.current_step == step.first
	end

	def self.generate_payment_code
		Training.last.id % PAYMENT_CODE_MOD_WEIGH
	end


	def price
		0
	end

	def payment_status				
		if amount_paid >= price
			PAYMENT_STATUSES[0]
		else
			PAYMENT_STATUSES[1]
		end
	end


	def total_price
		price + (payment_code || 0)
	end

	def amount_paid
		payments.empty? ? 0 : payments.confirmed.sum(:amount)
	end

	def amount_unpaid
		price - amount_paid 
	end

	def finish_training
		if score_changed?
			unless is_pass_test?
				initiate_post_test
			end
		end
	end

	def is_pass_test?
		score >= 70
	end

	def initiate_post_test
		if self.score >= 32.5
			self.status = Training::TRAINING_STATUSES[2]		
			self.attendee.send_post_test_invitation
		end
	end

	def is_need_post_test?
		status == Training::TRAINING_STATUSES[2]
	end

	def check_status_after_post_test
		if PostTestResult.passed_test?(self.id)
			self.status = Training::TRAINING_STATUSES[3]
			self.save
		end
	end

end


class RegularTraining < Training
	def price
		training_location.nil? ? 0 : training_location.price
	end

	def to_s
		"Training ATLS Regular"
	end	
end


class RemedialTraining < Training
	def price
		0
	end

	def to_s
		"Remedial Training"
	end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
	layout "home", :only => [:index, :show, :new, :create]
	before_filter :authenticate_attendee!


	def show		
		@training = Training.find(params[:id])
		respond_to do |format|
			format.json { render :json => @training}
			format.html{}
		end
	end

	def index
		# @att = Attendee.find(params[:id])
		# authorize! :read, @att		
		@trainings = current_attendee.trainings.sort_by_created_at
	end

	def new
		unless current_attendee.trainings.active_trainings.empty?
			flash[:error] = "Anda tidak dapat mendaftar training baru jika masih memiliki training yg aktif"
			redirect_to controller: :homes, action: :index
		end
		session[:training_params] ||= {}
		@training  = Training.new(session[:training_param])
	end

	def create				
		session[:training_params].deep_merge!(params[:training]) if params[:training]
		klass = session[:training_params]["type"]
		@training = klass.constantize.new(session[:training_params])
		@training.current_step = session[:current_step]	
		
		if params[:back_button]
			@training.previous_step
		elsif @training.last_step?
			@training.attendee = current_attendee
			payment = Payment.create(status: Payment.initial_status, amount: @training.price)
			@training.payments << payment
			@training.status = Training::TRAINING_STATUSES[1]
			@training.save
		else
			@training.next_step
			if(@training.current_step == "payment")
				session[:training_params].merge!("payment_code" => Training.generate_payment_code)
			end
		end

		session[:current_step] = @training.current_step
		if @training.new_record?
      		render 'new'
    	else
    		session[:current_step] = session[:training_params] = nil
	      	redirect_to :action => :index
    	end
	end

	def update
		@training = Training.find(params[:id])
		if params["training_date"]
			training_schedule = TrainingSchedule.find_by_training_date(Date.parse(params["training_date"]))
			@training.training_schedule = training_schedule
		end
		@training.update_attributes(params["training"])
		@training.save
		redirect_to :controller => :homes, :action => :index
	end

	def update_training_schedule
		if params["training_date"].blank?
			flash[:error] = "trainig schedule cannot be empty"
		else
			@training = Training.find(params[:id])
			training_date = Date.parse(params["training_date"])
			training_schedule = TrainingSchedule.find_by_training_location_and_training_date(@training.training_location, training_date.strftime("%F"))

			@training.training_schedule = training_schedule
			@training.save
		end
		
		redirect_to :action => :show, :id => @training.id
	end
end

app/helpers/trainings_helper.rb
module TrainingsHelper

	def training_types_for_select
		Training::TRAINING_TYPES.map{|t|[t]}
	end

	def training_location_for_select
		TrainingLocation.all.map{|t|["#{t.name}/Rp.#{t.price}", t.id]}
	end

	def payment_status_string(status)
		if status == Training::PAYMENT_STATUSES[3]
			return 'status-label-important'			
		elsif status == Training::PAYMENT_STATUSES[2] || status == Training::PAYMENT_STATUSES[1]
			return 'status-label-warning'
		elsif status == Training::PAYMENT_STATUSES[0]
			return 'status-label-success'
		end

	end
end

app/views/trainings/_details_steps.html.erb
<div class="heading">				
	<h1 class="heading-title">Daftar Training</h1>
	<div class="clearfix"></div>
</div>
<div class="border-bottom"></div>
<div>
	<div class="control-group row-fluid">                
		<label class="span3">Tipe training</label>
		<div class="control span8">  
			<%= f.select :type, options_for_select(training_types_for_select) %>                			
			<span class="help-inline"></span>
		</div>
	</div>
	<div class="control-group row-fluid">                
		<label class="span3">Lokasi training</label>
		<div class="control span8">                  
			<%= f.select :training_location_id, options_for_select(training_location_for_select) %>                			
			<span class="help-inline"></span>
		</div>
	</div>	
</div>

<% content_for :action_button do %>
  	<button type="submit" class="m-btn blue span3" type="button">Lanjut &gt</button>                   
<% end %>

app/views/trainings/_modal_training_schedule_select.html.erb
<%= form_for @training, :url => url_for(:action => "update_training_schedule"), :as => "training" do |f|%>
<div id="scheduleModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
		<h3 id="myModalLabel">Jadwal Training</h3>
	</div>
	
	<div class="modal-body">

		<div class="row-fluid price-section schedule-section" data-training-location= <%= @training.training_location.id %> >
			<div class="span12">						
				<div class="control-group">
					<label class="span3">Jadwal:</label>
					
						<div class="control span9">
							<input name="training_date" class="date-picker" type="text">
							<span class="help-inline"></span>
						</div>						
					
				</div>
			</div>
		</div>
	</div>

	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
		<button class="btn btn-primary">Pilih Jadwal</button>
	</div>			
</div>

<% end %>

app/views/trainings/_payment_steps.html.erb
<div class="heading">				
	<h1 class="heading-title">Pembayaran</h1>
	<div class="clearfix"></div>
</div>
<div class="border-bottom"></div>
<div>
	<div class="control-group row-fluid">                
		<label class="span3">Metode pembayaran</label>
		<div class="control span8">   
			<% PaymentType.all.each do |p| %>
				<div class="radio">
	  				<%= f.radio_button :payment_type_id, p.id, style: "width:auto" %>
	  				<span><%= "Transfer Bank #{p.name}" %></span>
				</div>				
			<% end %>
		</div>
	</div>

</div>

<% content_for :action_button do %>
	<button type="submit" name="back_button" class="m-btn red span3" type="button">&lt Kembali</button>                   
  	<button type="submit" class="m-btn blue span3" type="button">Lanjut &gt</button>                   
<% end %>

app/views/trainings/_summary_steps.html.erb
<div class="heading">				
	<h1 class="heading-title">Ringkasan</h1>
	<div class="clearfix"></div>
</div>
<div class="border-bottom"></div>
<div>
	<table class="table">
		<thead>
			<tr>								
				<th colspan="2">Barang</th>
				<th>Biaya</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td colspan="2"><%= @training.description %></td>												
				<td>Rp.<span class="pull-right"><%= number_to_currency_rupiah(@training.price) %> ,-</span></td>
			</tr>
			<tr>
				<td colspan="2">Kode pembayaran</td>						
				<td>Rp.<span class="pull-right"><%= number_to_currency_rupiah(@training.payment_code) %>,-</span></td>
			</tr>
			<tr>
				<td></td>
				<td class="pull-right strong">Total</td>						
				<td>Rp.<span class="pull-right strong"><%= number_to_currency_rupiah(@training.total_price)%>,-</span></td>
			</tr>					
		</tbody>
	</table>
	<div class="section">
		<label>Detail pembayaran</label>
		<p class="strong">Transfer Bank <%= "#{@training.payment_type.name}" %>  </p>
    	<p>No Rekening <%= "#{@training.payment_type.account_number}" %></p>
    	<p>Atas Nama <%= "#{@training.payment_type.account_holder}" %></p>
		<p>Cabang <%= "#{@training.payment_type.branch_name}" %></p>
	</div>

	<% content_for :action_button do %>
		<button type="submit" name="back_button" class="m-btn red span3" type="button">&lt Kembali</button>                   
	  	<button type="submit" class="m-btn blue span3" type="button">Lanjut &gt</button>                   
	<% end %>
</div>

app/views/trainings/index.html.erb
<% content_for :training_side_bar, "active" %>
<div class="container-fluid callout">
	<div class="row-fluid">
		<%= render "shared/side_bar" %>

		
		<div class="span9 contained">			
			<div class="heading">				
				<h2 class="heading-title">Trainings</h2>
				<%= link_to "Daftar", new_training_path, :class => "heading-button" %>
				<div class="clearfix"></div>
			</div>
			<div class="border-bottom"></div>			
			<div>			
				<% unless @trainings.blank? %>
					<table class="table">
					<thead>
						<tr>								
							<th>Tanggal Daftar</th>
							<th>Tipe Training</th>
							<!-- <th>Status Pembayaran</th> -->
						</tr>
					</thead>
					<tbody>
						<% @trainings.each do |training| %>
							<tr>
								<td><%= readable_date(training.created_at)%></td>
								<td><%= training.type %></td>
								<!-- <td><span class="status-label <%= payment_status_string(training.payment_status)%>"><%= training.payment_status %></span></td>	 -->
								<form accept-charset="UTF-8" action="/orders/104" class="edit_order" id="edit_order_104" method="post"></form> 
								<td>
									<%= link_to "", training_path(training), {:class => "magnifier-icon"} %>
								</td>						

							</tr>
						<% end %>					
					</tbody>
					</table>
				<% else %>
					<h4>Klik "Daftar" untuk mendaftar Training</h4>
				<% end %>
			</div>

		</div>
	</div>
</div>

app/views/trainings/new.html.erb
<div class="container-fluid callout">
	<div class="row-fluid" style="margin-top:30px;">		
		<%= render "/shared/side_bar" %>
		<div class="span9 contained">
			<%= form_for @training, :url => trainings_path, :as => "training" do |f| %>
				<%= render "#{@training.current_step}_steps", :f => f%>			 			 
				<div class="action-button row-fluid">
	     			<%= yield :action_button %>
	     		</div>
	     	<% end %>
		</div>
	</div>
</div>

app/views/trainings/show.html.erb
<div class="container-fluid callout">
	<div class="row-fluid" style="margin-top:30px;">
		<%= render "/shared/side_bar" %>
		<div class="span9 contained">
			<div class="heading">				
				<h1 class="heading-title">Training Detail</h1>
				<div class="clearfix"></div>
			</div>
			<div class="border-bottom"></div>		
			<div  class="section">			
				<div>
					<%= image_tag "magnifier-icon.png"%> <span class="section-heading">Detail<span>
				</div>
				
				<div class="data-item row-fluid">
		            <dt class="span6">Tipe Training</dt>
		            <dd class="span6"><%= @training.type%></dd>
          		</div>
          		<div class="data-item row-fluid">
		            <dt class="span6">Tanggal Daftar</dt>
		            <dd class="span6"><%= readable_date(@training.created_at) %></dd>
          		</div>          		
			</div>
			<div class="section">
				<div>
					<%= image_tag "money-bag-icon.png"%> <span class="section-heading">Pembayaran</span>
				</div>
				<div class="data-item row-fluid">
		            <dt class="span6">Status</dt>
		            <dd class="span6">
		            	<span class="status-label status-label-warning"><%= @training.payment_status %></span>
		            </dd>
          		</div>
				<div class="data-item row-fluid">
		            <dt class="span6">Biaya Training</dt>
		            <dd class="span6">Rp. <%= number_to_currency_rupiah(@training.price) %>,-</dd>
          		</div>
          		<div class="data-item row-fluid">
		            <dt class="span6">Kode Pembayaran</dt>
		            <dd class="span6">Rp.<%= number_to_currency_rupiah(@training.payment_code) %>,-</dd>
          		</div>
          		<div class="data-item row-fluid">
		            <dt class="span6">Total Biaya</dt>
		            <dd class="span6 strong">Rp.<%= number_to_currency_rupiah(@training.total_price) %>,-</dd>
          		</div>
          		<div class="data-item row-fluid">
		            <dt class="span6">Metode Pembayaran</dt>
		            <dd class="span6">
		            	<% if @training.payment_type %>
			            	<p class="strong">Transfer Bank <%= "#{@training.payment_type.name}" %>  </p>
			            	<p>No Rekening <%= "#{@training.payment_type.account_number}" %></p>
			            	<p>Atas Nama <%= "#{@training.payment_type.account_holder}" %></p>
							<p>Cabang <%= "#{@training.payment_type.branch_name}" %></p>
			            	<span class="subnote">pembayaran harus dilakukan dalam waktu maksimal 2x24 jam dari tanggal daftar. Jika lebih dari waktu yang ditetapkan, pendaftaran akan otomatis dibatalkan</span>
			            <% end %>
		            </dd>
          		</div>
			</div>
			<div class="section">			
				<div>
					<%= image_tag "calender-icon.png"%>  <span class="section-heading">Jadwal Training<span>
				</div>
				
				<div class="data-item row-fluid">
		            <dt class="span6">Tanggal Training
		            	<span class="subnote">pembayaran harus diselesikan terlebih dahulu untuk bisa memilih jadwal</span>
		            </dt>		            
		            <dd class="span3"><%= @training.training_schedule ? readable_date(@training.training_schedule.training_date) : "Not Selected" %></dd>
		            <a href="#" id="select-schedule" class="body-button">Pilih Jadwal</a>
          		</div>          		
			</div>

			<div class="section">			
				<div>
					<span class="section-heading">Hasil Training<span>
				</div>
				
				<div class="data-item row-fluid">
		            <dt class="span6">Nilai Test		            	
		            </dt>		            
		            <dd class="span3"><%= @training.score ? @training.score : "-" %> </dd>
          		</div>          		
          		<div class="data-item row-fluid">
		            <dt class="span6">Status Training		            	
		            </dt>		            
		            <dd class="span3"><%= @training.status ? @training.status : "-" %> </dd>
          		</div>          		
			</div>
		</div>
	</div>
</div>

<%= render "modal_training_schedule_select" %>