config/routes.rb
require 'sidekiq/web'

AtlsRails::Application.routes.draw do
  root :to => 'high_voltage/pages#show', :id => 'index'
  devise_for :attendees, :controllers => { 
    :registrations => "attendees"}

  devise_scope :attendee do
    get '/attendees/new' => "attendees#new", :as => "sign_up"
  end


  get "profiles/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :blogs
  
  resources :orders

  resources :pretests

  resources :test_results

  resources :training_schedules, :only => [:index, :show]

  resources :trainings

  resources :events

  resources :news

  match "/trainings/:id/update_training_schedule" => "trainings#update_training_schedule", via: :put

  match "/home" => "homes#index"
  match "/home/test" => "homes#test"
  match "/home/start_test" => "homes#start_test"
  match "/home/finish_test" => "homes#finish_test"

  match "/home/profile/:id" => "homes#edit_profile", via: :get
  
  match "/home/profile/:id" => "homes#update_profile", via: :put

  match "/home/profile/:id/change_password" => "homes#change_password", via: :get

  match "/home/profile/:id/change_password" => "homes#update_password", via: :put

  match "/payment_term" => "homes#payment_terms"

  match "/payment_code" => "orders#payment_code"

  namespace :home do
    resources :post_tests do
      collection do 
        get :start_test
      end      
    end
  end


  mount Sidekiq::Web => '/sidekiq'

end

app/views/shared/_side_bar.html.erb
<ul class="nav nav-list span2 contained">
	<li class="nav-header">Menu</li>
	<li class="<%= yield :home_side_bar %>">
		<%= link_to "Home", :controller => "/homes", :action => "index" %>
	</li>

	<li class="<%= yield :pretest_side_bar %>">
		<%= link_to "Pretest", home_test_path %>
	</li>
	<li class="<%= yield :edit_profile_side_bar %>">				
		<%= link_to "Edit Profile", :controller => "/homes", :action => "edit_profile", :id => current_attendee.id %>
	</li>

	<li class="<%= yield :change_password_side_bar %>">				
		<%= link_to "Change Password", :controller => "/homes", :action => "change_password", :id => current_attendee.id%>
	</li>
</ul>