config/routes.rb
require 'sidekiq/web'

AtlsRails::Application.routes.draw do
  root :to => 'high_voltage/pages#show', :id => 'index'
  devise_for :attendees, :controllers => { 
    :registrations => "attendees"}

  devise_scope :attendee do
    get '/attendees/new' => "attendees#new", :as => "sign_up"
  end


  get "profiles/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :blogs
  
  resources :orders

  resources :pretests

  resources :test_results

  resources :training_schedules, :only => [:index, :show]

  resources :trainings

  resources :events

  resources :news

  match "/trainings/:id/update_training_schedule" => "trainings#update_training_schedule", via: :put

  match "/home" => "homes#index"
  match "/home/test" => "homes#test"
  match "/home/start_test" => "homes#start_test"
  match "/home/finish_test" => "homes#finish_test"

  match "/home/profile/:id" => "homes#edit_profile", via: :get
  
  match "/home/profile/:id" => "homes#update_profile", via: :put

  match "/home/profile/:id/change_password" => "homes#change_password", via: :get

  match "/home/profile/:id/change_password" => "homes#update_password", via: :put

  match "/payment_term" => "homes#payment_terms"

  match "/payment_code" => "orders#payment_code"

  namespace :home do
    resources :post_tests do
      collection do 
        get :start_test
      end      
    end
  end


  mount Sidekiq::Web => '/sidekiq'

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [ :email ]

  #overide for password= method in database_authenticable devise module
  include PasswordUnhash

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :orders, :orders_attributes, :training_attributes, :cell_number, :campus, :plain_password
  attr_accessible :address, :campus_address, :campus_name, :campus_phone, :date_of_birth, :email, :gender, :job_title, :name, :office_address, :office_name, :office_phone, :phone, :religion, :place_of_birth, :order, :campus_id, :book_status, :graduation_year

  attr_reader :state
  

  has_many :orders
  has_many :test_results
  belongs_to :campus
  has_many :trainings
  accepts_nested_attributes_for :orders
  validates_presence_of :address, :gender, :name, :message => '%{value} need to be set'
  validates_presence_of :phone, :message => '%{value} need to be set'

  validates_uniqueness_of :email, :message => '%{value}'

  scope :by_training_location, lambda{|location| joins(:trainings).where('trainings.training_location_id = ?', location.id) }
  scope :by_training_locations, lambda{|locations| joins(:trainings).where('trainings.training_location_id in (?)', locations) }
  scope :by_training_schedule, lambda{|schedule| joins(:trainings).where('trainings.training_schedule_id = ?', schedule.id) }
  scope :payment_completed, lambda{ joins(:training).where('trainings.payment_status = ?', Training::PAYMENT_STATUSES[0])}
  scope :pretest_completed, joins(:test_results).uniq
  
  delegate :training_location, to: :training

  BOOK_STATUS = %w(Dikirim Diambil)

  DEFAULT_PASSWORD = "password01"

  def self.eligable_attendee_by_training_schedule(training_schedule)
    Attendee.by_training_schedule(training_schedule)
  end

  def available_payment_term
    last_order = self.orders.completed.latest == nil ? nil : self.orders.completed.latest.first

    if last_order 
      if last_order.payment_term == PaymentTerm.find_by_name(PaymentTerm::TERM_FIRST_INSTALLMENT)
        @payment_term = PaymentTerm.where("name = ?", PaymentTerm::TERM_SECOND_INSTALLMENT)   
      end
    else
      @payment_term = PaymentTerm.where("name = ? OR name = ?", PaymentTerm::TERM_FIRST_INSTALLMENT, PaymentTerm::TERM_FULL_PAYMENT)   
    end
  end

  def self.create_default_attendee(attributes)  
    attributes.merge! password: "password01", password_confirmation: "password01"
    attendee = Attendee.new(attributes)
    attendee.save!
  end

  def self.create_multiple_attendees(attendees_array)
    transaction do
        attendees_array.each do |a|
            a.merge! password: "password01", password_confirmation: "password01"
            attendee = Attendee.new(a)
            attendee.save!
        end
    end
  end

  def self.import
    exl = Roo::Excelx.new("/Users/aviandrihidayat/Documents/projects/atls-rails/atls-sample.xlsx")    
    ((exl.first_row+2)..exl.last_row).each do |i|
      name = exl.cell(i, "B") 
      phone = exl.cell(i, "C")
      campus_name = exl.cell(i, "D")
      campus = Campus.find_by_name(campus_name)      
      office_name = exl.cell(i, "F")
      email = exl.cell(i, "E") || "" + SecureRandom.hex(10) + "@mail.com"
      password = SecureRandom.hex(10)
      dob = "11-08-1984"
      gender = "male"
      address = "Matraman"
      place_of_birth = "Jakarta"


      first_payment = exl.cell(i, "G") || 0
      second_payment = exl.cell(i, "K") || 0
      training_location_name = exl.cell(i, "P")
      training_location = TrainingLocation.find_by_name(training_location_name)
       
      attendee = Attendee.new(:name => name, :phone => phone, 
        :campus => campus, :office_name => office_name,
        :email => email, password: password, password_confirmation: password, date_of_birth: dob, gender: gender, address: address, place_of_birth: place_of_birth)          

      payment_amount = first_payment + second_payment

      training = Training.new(:type => "RegularTraining", training_location: training_location, amount_paid: payment_amount)

      attendee.trainings << training
      a = attendee.save
    end

  end

  def self.create_attendee_with_completed_payment(attendee_attr)
    transaction do 
      attendee_attr = attendee_attr.merge(password: DEFAULT_PASSWORD, password_confirmation: DEFAULT_PASSWORD)
      training = Training.new(attendee_attr[:training_attributes])

      attendee = Attendee.new(attendee_attr)
      attendee.training = training

      Order.create_completed_payment_order(attendee, training.training_location)
      attendee.save
      return attendee
    end    
  end

  def self.update_attendee_with_completed_payment(attendee_id, attendee_attr)
    attendee = Attendee.find attendee_id
    attendee.update_attributes(attendee_attr)
    attendee
  end

  def create_completed_order(training_location_id)
    training_location = TrainingLocation.find(training_location_id)
    order = Order.new(attendee: self.id)
  end

  def training_location_name
    self.training_location.name
  end

  def is_complete_pretest?
    !test_results.blank?
  end

  def generate_new_password_email
    self.send_reset_password_instruction
  end


  def send_post_test_invitation
      self.send_reset_password_instructions
      @state = "PostTestInvite"
  end

  def find_latest_post_test_training
      trainings.post_test_trainings ? trainings.post_test_trainings.last : nil
  end

  def send_devise_notification(notification, *args)
      # devise_mailer.send(notification, self, *args).deliver

      SendResetPasswordWorker.perform_async(self.id, args[0])
  end


  # protected
  # def password=(new_password)
  #     binding.pry
  #     @password = new_password
  #     self.encrypted_password = password_digest(@password) if @password.present?
  # end

  private
  def create_training  
      unless self.training        
        self.training = Training.new
      end
  end

end

app/controllers/attendees_controller.rb
class AttendeesController < Devise::RegistrationsController
	before_filter :authenticate_attendee!, :except => [:new, :create, :mandiri, :update]
	layout "attendee", :only => [:home]

	def new
		@attendee = Attendee.new
	end

	def create
		resource.update_attributes(params["attendee"])
		super
	end

	def update
		@attendee = Attendee.find(params[:id])

		if params["training_location"]
			@attendee.training.training_location = TrainingLocation.find(params["training_location"])
			@attendee.training.save
		end		
		@attendee.update_attributes(params["attendee"])		
		@attendee.save
		redirect_to :controller => :homes, :action => :index
	end

	def home

	end

	def resource_name
		:attendee
	end

	def resource
		@resource ||= Attendee.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:attendee]
	end

	protected

	def after_sign_up_path_for(resource)
		if resource.class.name == "Attendee"
			trainings_path
		else
			super
		end
	end

	private

end

app/helpers/attendees_helper.rb
module AttendeesHelper

	def has_error(name, obj)
		if obj.errors.any?
			if obj.errors[name.to_sym].any?
				return 'error'
			end
		end
	end

	def get_error_message(name, obj)
		if obj.errors.any?
			if obj.errors[name.to_sym].any?
				obj.errors.messages[name.to_sym].first			
			end
		end
	end

end

app/views/attendees/home.html.erb
<div class="container-fluid">
	<div class="row-fluid" style="margin-top:30px;">
		<ul class="nav nav-list span2 wrapper shadow">
			<li class="nav-header">Menu</li>
			<li class="active"><a href="home1.html">Home</a></li>
			<li><a href="test_home.html">Pretest</a></li>
			<li><a href="#">Edit Profile</a></li>
		</ul>
		
		<div class="span10" style="padding:10px 10px 10px 10px;">
			<div class="payment-section wrapper shadow">
				<div class="row-fluid section-title">				
					<div class="span9">
						<h3>Kursus ATLS</h3>					
					</div>
					<div class="span3" style="margin-top:1%;">
						<button type="button" data-toggle="modal" data-target="#myModal" class="btn btn-success">Daftar</button>					
					</div>
				</div>


				<div class="row-fluid">				
					<div class="span9">
						<span class="label-title">Pembayaran</span>									
					</div>
					<div class="span3">
						<span class="label section-status label-warning">incomplete</span>	
					</div>
				</div>	

				<div class="row-fluid table">
					<div class="span10">
						<table class="table table-striped">
							<thead>
								<tr>								
									<th>Order</th>
									<th>Tanggal Daftar</th>
									<th>Status</th>									
								</tr>
							</thead>
							<tbody>
								<% @orders.each_with_index do |order, index|%>
								<tr>
									<td><%= index + 1 %></td>
									<td><%= order.created_at.strftime("%d-%m-%Y") %></td>
									<td><span class="label <%= order_label_string(order.status) %>"><%= order.status %></span></td>	
									<td>
										<button type="button" data-toggle="modal" data-target="#myModal" class="btn btn">Detail</button>
										<button type="button" data-toggle="modal" data-target="#myModal" class="btn btn">Batal</button>

									</td>								
								</tr>
								<% end %>
								<tr>
									<td>2</td>
									<td>14 Mei 2013</td>
									<td><span class="label label-warning">pending</span></td>	
									<td>
										<button type="button" data-toggle="modal" data-target="#myModal" class="btn btn-success">Detail</button>
										<button type="button" data-toggle="modal" data-target="#myModal" class="btn btn">Batal</button>
									</td>							
								</tr>
								
							</tbody>
						</table>
					</div>
				</div>	
			</div>

			<div class="pretest-section wrapper shadow">
				<div class="row-fluid section-title">				
					<div class="span9">
						<h3>Pre-Test</h3>					
					</div>
					<div class="span3" style="margin-top:1%;">
						<button type="button" data-toggle="modal" class="btn btn-success">Test</button>
					</div>
				</div>

				<div class="row-fluid">				
					<div class="span9">
						<span class="label-title">Pre-Test</span>									
					</div>
					<div class="span3">
						<span class="label section-status label-warning">incomplete</span>	
					</div>
				</div>		
			</div>

			<div class="schedule-location-section wrapper shadow">
				<div class="row-fluid section-title">				
					<div class="span9">
						<h3>Jadwal dan Lokasi</h3>					
					</div>
					<div class="span3" style="margin-top:1%;">
						<button disabled="true" type="button" data-toggle="modal" class="btn btn-success">Pilih</button>
					</div>
				</div>

				<div class="row-fluid">				
					<div class="span9">
						<span class="label-title">Lokasi</span>									
					</div>
					<div class="span3">
						Jakarta
					</div>						
				</div>	
				<div class="row-fluid">				
					<div class="span9">
						<span class="label-title">Jadwal</span>									
					</div>
					<div class="span3">
						11 Maret 2013
					</div>						
				</div>		
			</div>
		</div>

	</div>		

	<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
			<h3 id="myModalLabel">Pembayaran</h3>
		</div>
		<div class="modal-body">
			<div class="row-fluid">
				<div class="span6">
					<span>Methode Pembayaran</span>
				</div>
				<div class="span6">
					<select>
						<option>Transfer</option>
						<option>Credit Card</option>
					</select>
				</div>
			</div>

			<div class="row-fluid price-section">
				<div class="span12">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>#</th>
								<th>Product</th>
								<th>Harga</th>									
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>1</td>
								<td>Biaya Kursus</td>
								<td>Rp.4000.000,-</td>										
							</tr>
							<tr>
								<td>2</td>
								<td>ID Transaksi</td>
								<td>Rp.1,-</td>
							</tr>		
							<tr>
								<td>Total</td>
								<td></td>
								<td><span class="strong">Rp.4000.001,-</span></td>
							</tr>									
						</tbody>
					</table>
				</div>
			</div>

			<div class="row-fluid price-section">
				<div class="span12">
					<span>Transfer the payment to:</span>
					<span>Bank BCA</span>
					<span>Account Number 4111111111111111</span>
				</div>
			</div>

		</div>
		<div class="modal-footer">
			<%= form_for @order do|f| %>
			<button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
			<button class="btn btn-primary">Make Order</button>
			<% end %>
		</div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function(){
	$("a").popover({"placement":"top"});	
});

</script>

app/views/attendees/new.html.erb
<div class="row-fluid callout body">
  <div class="container-fluid">              
    <div id="register-form" class="span8 offset2">        
      <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |b| %>
      <%= devise_error_messages! %>
      <fieldset>
        <legend>Account</legend>
        <div class="control-group <%= has_error('email', @attendee) %>" >
          <label>Email:</label>
          <div class="control">                  
            <%= b.email_field :email, :class => "span6" , :placeholder => "johndoe@gmail.com" %>
            <span class="help-inline"><%= get_error_message('email', @attendee) %></span>
          </div>
        </div>
        <div class="control-group <%= has_error('password', @attendee) %>">
          <label>Password:</label>
          <div class="control">
            <%= b.password_field :password, :class=> "span6"%>
            <span class="help-inline"><%= get_error_message('password', @attendee) %></span>
          </div> 
        </div>
        <div class="control-group">
          <label>Confirm Password:</label>
          <div class="control">
            <%= b.password_field :password_confirmation, :class=> "span6"%>
          </div> 
        </div>

        <legend>Biodata</legend>

       <div class="control-group <%= has_error('name', @attendee) %>" >                
          <label>Nama Lengkap:</label>
          <div class="control">                  
            <%= b.text_field :name%>
            <span class="help-inline"><%= get_error_message('name', @attendee) %></span>
          </div>
        </div>                            

        <div class="control-group <%= has_error('date_of_birth', @attendee) %>">                
          <label>Tanggal Lahir:</label>
          <div class="control">                  
            <%= b.text_field :date_of_birth, :class => "date-picker" %>
            <span class="help-inline"><%= get_error_message('date_of_birth', @attendee) %></span>
          </div>                                
        </div>


        <div class="control-group <%= has_error('place_of_birth', @attendee) %>">
          <label>Tempat Lahir:</label>
          <div class="control">                  
            <%= b.text_field :place_of_birth%>
            <span class="help-inline"><%= get_error_message('place_of_birth', @attendee) %></span>
          </div>                                
        </div>

        <div class="control-group <%= has_error('gender', @attendee) %>">                
          <label>Gender:</label>
          <div class="control">
            <%= b.select :gender, options_for_select([["Pria", "male"], ["Wanita", "female"]]) %>
            <span class="help-inline"><%= get_error_message('gender', @attendee) %></span> 
          </div>                                                
        </div>


        <div class="control-group <%= has_error('religion', @attendee) %>">
          <label>Agama:</label>
          <div class="control">
            <%= b.select :religion, options_for_select([["Islam", "islam"], ["Kristen", "kristen"], ['Hindu', "hindu"], ['Budha', 'budha']]) %>
            <span class="help-inline"><%= get_error_message('religion', @attendee) %></span>
          </div>
        </div>


        <div class="control-group <%= has_error('attendee.address', @attendee) %>">              
          <label>Alamat:</label>
          <div class="control">
            <%= b.text_field :address, :class => "span8" , :placeholder => "Jl. Setra duta raya E1-18" %>
            <span class="help-inline"><%= get_error_message('address', @attendee) %></span>
          </div>
        </div>


        <div class="control-group <%= has_error('phone', @attendee) %>">              
          <label>Telepon:</label>
          <div class="control">
            <%= b.text_field :phone, :class => "span4" , :placeholder => "021-200000 atau 0821111111" %>
            <span class="help-inline"><%= get_error_message('phone', @attendee) %></span>
          </div>
        </div>


        <legend>Data Kantor</legend>

        <div class="control-group <%= has_error('office_name', @attendee) %>">              
          <label>Nama Kantor:</label>
          <div class="control">
            <%= b.text_field :office_name, :class => "span4" , :placeholder => "Departemen Kesehatan" %>
            <span class="help-inline"><%= get_error_message('office_name', @attendee) %></span>
          </div>                
        </div>

        <div class="control-group <%= has_error('office_address', @attendee) %>">              
          <label>Alamat Kantor</label>                
          <div class="control">                
            <%= b.text_field :office_address, :class => "span8" , :placeholder => "Jalan Kesehatan No.11" %>
            <span class="help-inline"><%= get_error_message('office_address', @attendee) %></span>
          </div>
        </div>


        <div class="control-group <%= has_error('office_address', @attendee) %>">
          <label>Telepon Kantor</label>
          <div class="control">
            <%= b.text_field :office_phone, :class => "span4" , :placeholder => "021-200000 atau 0821111111" %>
            <span class="help-inline"><%= get_error_message('office_phone', @attendee) %></span>
          </div>
        </div>


        <div class="control-group <%= has_error('job_title', @attendee) %>">
          <label>Jabatan</label>
          <div class="control">
            <%= b.text_field :job_title, :class => "span4" , :placeholder => "Dokter Umum" %>
            <span class="help-inline"><%= get_error_message('job_title', @attendee) %></span>
          </div>                
        </div>

        <legend>Kampus</legend>


        <div class="control-group <%= has_error('campus_name', @attendee) %>">
          <label>Kampus</label>            
          <div class="control">
            <%= b.collection_select :campus_id, Campus.sort_by_name, :id, :name %>
            <span class="help-inline"><%= get_error_message('campus', @attendee) %></span>
          </div>
        </div>

        
      </fieldset>
       <div class="span10 pagination-centered" id="submit-button">
         <button class="m-btn blue" type="button">Lanjut></button>                   
      </div>
      <% end %>      
      
    </div>        
  </div>
</div>

<!-- FOOTER -->
<div class="row-fluid">

  <div class="container footer">

    <!-- Copyright and contact -->

    <div class="span4 address">

      ©2013 <a href="http://www.itoz-labs.com">ItoZLabs </a>

    </div>

    <!-- newsletter form -->

    <div class="span5 pull-right footer-newsletter">
      <h2>Newsletter</h2>
      <p>Subscribe to our newsletter and get the latest news!</p>
      <form action="mail.php" id="subscribe-form" method="post">
        <input type="text" name="email" id="email" placeholder="Your Email Address" class="input-text m-wrap m-ctrl">
        <button type="submit" class="m-btn blue">Sign Up</button>
      </form>
    </div>

  </div>
</div>

<script type="text/javascript">
$(document).ready(function(){
  $("#submit-button").bind("click", function(){
    $("#new_attendee").submit();
  });
});
</script>

app/views/attendees/sign_in.erb
<div class="row-fluid callout">
  <!-- Start Carousel -->
  <div class="container-fluid">
    <div id="register-form" class="span5">        
      <fieldset>
        <legend>Login</legend>
        <div id="register-form-input" class="span12">
          <%= form_for(@attendee, :url => attendee_session_path) do |f| %>
          <div class="control-group">
            <div class="control">
              <%= f.email_field :email, :placeholder=>"Enter your e-mail address", :class => "span12 field" %>                  
            </div>
          </div>

          <div class="control-group">
            <div class="control">    
              <%= f.password_field :password, :placeholder => "Enter your password", :class => "span12 field" %>              
            </div>
          </div>
          <div class="control-group">
            <div class="controls">
              <label class="checkbox span4 offset7">
                <input type="checkbox"> Remember me
              </label>
              <%= render "devise/shared/links" %>
              <button type="submit" class="pull-right m-btn blue">Sign in</button>
            </div>
          </div>    
          <% end %>   
        </div>         
      </fieldset>
      <div class="row">
        <span class="span9 offset2">Belum punya account? <a href="http://google.com">Sign up</a> terlebih dahulu</span>
      </div>
      
    </div>


  </div>
</div>

<!-- FOOTER -->
<div class="row-fluid">

  <div class="container footer">

    <!-- Copyright and contact -->

    <div class="span4 address">

      ©2013 <a href="http://www.itoz-labs.com">ItoZLabs </a>

    </div>

    <!-- newsletter form -->

    <div class="span5 pull-right footer-newsletter">
      <h2>Newsletter</h2>
      <p>Subscribe to our newsletter and get the latest news!</p>
      <form action="mail.php" id="subscribe-form" method="post">
        <input type="text" name="email" id="email" placeholder="Your Email Address" class="input-text m-wrap m-ctrl">
        <button type="submit" class="m-btn blue">Sign Up</button>
      </form>
    </div>

  </div>
</div>