config/routes.rb
require 'sidekiq/web'

AtlsRails::Application.routes.draw do
  root :to => 'high_voltage/pages#show', :id => 'index'
  devise_for :attendees, :controllers => { 
    :registrations => "attendees"}

  devise_scope :attendee do
    get '/attendees/new' => "attendees#new", :as => "sign_up"
  end


  get "profiles/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :blogs
  
  resources :orders

  resources :pretests

  resources :test_results

  resources :training_schedules, :only => [:index, :show]

  resources :trainings

  resources :events

  resources :news

  match "/trainings/:id/update_training_schedule" => "trainings#update_training_schedule", via: :put

  match "/home" => "homes#index"
  match "/home/test" => "homes#test"
  match "/home/start_test" => "homes#start_test"
  match "/home/finish_test" => "homes#finish_test"

  match "/home/profile/:id" => "homes#edit_profile", via: :get
  
  match "/home/profile/:id" => "homes#update_profile", via: :put

  match "/home/profile/:id/change_password" => "homes#change_password", via: :get

  match "/home/profile/:id/change_password" => "homes#update_password", via: :put

  match "/payment_term" => "homes#payment_terms"

  match "/payment_code" => "orders#payment_code"

  namespace :home do
    resources :post_tests do
      collection do 
        get :start_test
      end      
    end
  end


  mount Sidekiq::Web => '/sidekiq'

end

app/models/training.rb
class Training < ActiveRecord::Base
	attr_accessible :training_location, :attendee_id, :amount_paid, :amount_unpaid, :training_location_id, :training_schedule_id, :payment_type_id, :payment_code, :type, :status, :description, :payments_attributes, :group_number, :score
	attr_writer :current_step

	scope :by_training_schedule, lambda{|schedule| joins(:training).where('trainings.training_schedule_id = ?', schedule.id) }

	belongs_to :training_location
	belongs_to :attendee
	belongs_to :training_schedule

	belongs_to :payment_type
	has_many :payments

	has_many :post_test_results

	after_initialize :init
	accepts_nested_attributes_for :training_location, :payments

	PAYMENT_STATUSES = %w(Lunas Belum\ Lunas)	

	TRAINING_STATUSES = %w(Batal Aktif PostTest Lulus)

	TRAINING_TYPES = %w(RegularTraining RemedialTraining)

	PAYMENT_CODE_MOD_WEIGH = 200

	scope :sort_by_created_at, order("created_at desc")
	scope :post_test_trainings, where(status: Training::TRAINING_STATUSES[2])
	scope :active_trainings, where("status = ? OR status = ?", Training::TRAINING_STATUSES[1], Training::TRAINING_STATUSES[2])

	before_save :finish_training


	def init
		unless self.amount_paid
			self.amount_paid = 0			
		end		
	end


	# def self.create_initial_training(attributes)
	# 	training = Training.new(attributes.select{|s,value|value.nil? == false})
	# 	training.status = Training::TRAINING_STATUSES[1]
	# 	training.save
	# end

	def confirm_payment
		self.amount_paid = self.total_price
		self.save
	end

	def payment_done?
		unless training_location
			return false
		end
		if amount_paid >= training_location.price
			true
		else
			false
		end
	end


	def steps
		%w[details payment summary]
	end

	def current_step
		@current_step || steps.first
	end

	def next_step
		self.current_step = steps[steps.index(current_step)+1]
	end

	def previous_step
		self.current_step = steps[steps.index(current_step)-1]
	end

	def last_step?
		self.current_step == steps.last
	end

	def first_step?
		self.current_step == step.first
	end

	def self.generate_payment_code
		Training.last.id % PAYMENT_CODE_MOD_WEIGH
	end


	def price
		0
	end

	def payment_status				
		if amount_paid >= price
			PAYMENT_STATUSES[0]
		else
			PAYMENT_STATUSES[1]
		end
	end


	def total_price
		price + (payment_code || 0)
	end

	def amount_paid
		payments.empty? ? 0 : payments.confirmed.sum(:amount)
	end

	def amount_unpaid
		price - amount_paid 
	end

	def finish_training
		if score_changed?
			unless is_pass_test?
				initiate_post_test
			end
		end
	end

	def is_pass_test?
		score >= 70
	end

	def initiate_post_test
		if self.score >= 32.5
			self.status = Training::TRAINING_STATUSES[2]		
			self.attendee.send_post_test_invitation
		end
	end

	def is_need_post_test?
		status == Training::TRAINING_STATUSES[2]
	end

	def check_status_after_post_test
		if PostTestResult.passed_test?(self.id)
			self.status = Training::TRAINING_STATUSES[3]
			self.save
		end
	end

end


class RegularTraining < Training
	def price
		training_location.nil? ? 0 : training_location.price
	end

	def to_s
		"Training ATLS Regular"
	end	
end


class RemedialTraining < Training
	def price
		0
	end

	def to_s
		"Remedial Training"
	end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
	layout "home", :only => [:index, :show, :new, :create]
	before_filter :authenticate_attendee!


	def show		
		@training = Training.find(params[:id])
		respond_to do |format|
			format.json { render :json => @training}
			format.html{}
		end
	end

	def index
		# @att = Attendee.find(params[:id])
		# authorize! :read, @att		
		@trainings = current_attendee.trainings.sort_by_created_at
	end

	def new
		unless current_attendee.trainings.active_trainings.empty?
			flash[:error] = "Anda tidak dapat mendaftar training baru jika masih memiliki training yg aktif"
			redirect_to controller: :homes, action: :index
		end
		session[:training_params] ||= {}
		@training  = Training.new(session[:training_param])
	end

	def create				
		session[:training_params].deep_merge!(params[:training]) if params[:training]
		klass = session[:training_params]["type"]
		@training = klass.constantize.new(session[:training_params])
		@training.current_step = session[:current_step]	
		
		if params[:back_button]
			@training.previous_step
		elsif @training.last_step?
			@training.attendee = current_attendee
			payment = Payment.create(status: Payment.initial_status, amount: @training.price)
			@training.payments << payment
			@training.status = Training::TRAINING_STATUSES[1]
			@training.save
		else
			@training.next_step
			if(@training.current_step == "payment")
				session[:training_params].merge!("payment_code" => Training.generate_payment_code)
			end
		end

		session[:current_step] = @training.current_step
		if @training.new_record?
      		render 'new'
    	else
    		session[:current_step] = session[:training_params] = nil
	      	redirect_to :action => :index
    	end
	end

	def update
		@training = Training.find(params[:id])
		if params["training_date"]
			training_schedule = TrainingSchedule.find_by_training_date(Date.parse(params["training_date"]))
			@training.training_schedule = training_schedule
		end
		@training.update_attributes(params["training"])
		@training.save
		redirect_to :controller => :homes, :action => :index
	end

	def update_training_schedule
		if params["training_date"].blank?
			flash[:error] = "trainig schedule cannot be empty"
		else
			@training = Training.find(params[:id])
			training_date = Date.parse(params["training_date"])
			training_schedule = TrainingSchedule.find_by_training_location_and_training_date(@training.training_location, training_date.strftime("%F"))

			@training.training_schedule = training_schedule
			@training.save
		end
		
		redirect_to :action => :show, :id => @training.id
	end
end

app/helpers/trainings_helper.rb
module TrainingsHelper

	def training_types_for_select
		Training::TRAINING_TYPES.map{|t|[t]}
	end

	def training_location_for_select
		TrainingLocation.all.map{|t|["#{t.name}/Rp.#{t.price}", t.id]}
	end

	def payment_status_string(status)
		if status == Training::PAYMENT_STATUSES[3]
			return 'status-label-important'			
		elsif status == Training::PAYMENT_STATUSES[2] || status == Training::PAYMENT_STATUSES[1]
			return 'status-label-warning'
		elsif status == Training::PAYMENT_STATUSES[0]
			return 'status-label-success'
		end

	end
end

app/views/admin/trainings/_form.html.erb
<%= semantic_form_for [:admin, @training],  :url => url_for(:controller => "admin/trainings", :action => params[:action].start_with?("new", "create")  ? "create" : "update" ) , :as => "training" do |f| %>
		<%= f.inputs "Training Details" do %>
				<%= f.input :attendee, :as => :select, :include_blank => false, :collection => params["attendee_id"] ? [[Attendee.find(params["attendee_id"]).name, Attendee.find(params["attendee_id"]).id]] : Attendee.all.map{|a| [a.name, a.id]} %>
				<%= f.input :type, :as => :select, :include_blank => false, :collection => Training::TRAINING_TYPES , :include_blank => false %>
	 			<%= f.input :training_location_id, :as => :select, :include_blank => false, :collection => Hash[TrainingLocation.all.map{|b|["#{b.name}/Rp.#{b.price}",b.id]}], :include_blank => false %>
	 			<%= f.input :training_schedule_id, :as => :select, :include_blank=> false, :collection => TrainingLocation.first ?  TrainingLocation.first.training_schedules.map{|b|[b.training_date, b.id]} : []  %>
	 			<%= f.input :group_number, :as => :select, :collection => f.object.group_number ?  [f.object.group_number] : [] %>
	 			<%= f.input :status, :as => :select, :collection => Training::TRAINING_STATUSES %>
	 			<%= f.input :description, :as => :text %>	 
	 	<% end %>
	 	<%= f.inputs "Test Detail" do %>
	 			<%= f.input :score %>
	 	<% end %>
		<%= f.inputs "Pembayaran" do %>
			<ol>
				<li class="action">
					<input name="add_payment" id="add_payment" type="button" value="Create Payment">
				</li>
			</ol>
			
				<%= f.inputs do %>

					<%= f.semantic_fields_for :payments do |payment| %>
						<div id="payments-container">
							<div class="payment_input" data-action="<%= params[:action] %>">
				 				<%= payment.input :payment_date, :input_html => {:class => "datepick"}, :as => "string" %>
				 				<br>
				 				<%= payment.input :status, as: :select, collection: Payment::PAYMENT_STATUS  %>
				 				<br>
				 				<%= payment.input :amount %>
			 					<br>
			 					<ol>
									<li class="action">
										<% if payment.object.new_record? %>
											<%= link_to 'Remove', '', :remote => true, :class => 'destroy_duplicate_nested_form' %>
										<% else %>
											<%= link_to 'Remove', admin_payment_path(payment.object), :method => :delete, :remote => true, :class => 'destroy_duplicate_nested_form' %>
										<% end %>
									</li>
								</ol>
								<br>
							</div>
						</div>
					<% end %>
				<% end %>			 			
 		<% end %>
	 	<%= f.actions %>
<% end %>



<script type="text/javascript">
	$("#training_training_location_id").change(function(){
		var callback = function(response){
			var test = $("#training_training_schedule_id").find('option').remove();
			var training_schedules = response.training_schedules;
			$("#training_training_schedule_id").append($("<option></option>"));

			for(var i = 0; i < training_schedules.length ; i++){
				$("#training_training_schedule_id")
				.append($("<option></option>")
						.attr("value", training_schedules[i].id)
						.text(training_schedules[i].training_date));				
			}			
		}
		$.get('/training_schedules?training_location_id='+$(this).val(), callback, 'json');
	});

	$("#training_training_schedule_id").change(function(){
		var callback = function(response){
			$("#training_group_number").find('option').remove();
			for(var i = 0; i < response.number_of_group ; i++){
				$("#training_group_number")
				.append($("<option></option>")
						.attr("value", i + 1)
						.text(i+1));				
			}	
		}
		$.get('/training_schedules/'+$(this).val(), callback, 'json');
	});

	$(document).ready(function(){
		$("body").on("click", ".datepick",  function(){
	    	 $(".datepick").datepicker({ 
	    	 	dateFormat: "dd-mm-yy"
    		});
		});
	});


	
	
</script>

app/views/admin/trainings/index.html.erb
<table>
  <thead>
    <tr>
      <th><%= sort_link @search, :id, "id" %></th>
      <th><%= sort_link @search, :attendee, "Attendee" %></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @trainings.each do |page| %>
      <tr>
        <td><%= training.id %></td>
        <td><%= training.attendee.name %></td>
        <!-- <td><%= link_to("Update",edit_admin_page_path(page)) %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>